# Generated by Django 4.0.3 on 2022-04-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='subcategory',
        ),
    ]
